### ISSUE TITLE
Обсуждение зависимости от `.env`

### ISSUE THREAD

**Issue by iamsalnikov** [liverecord/server#2]
Здесь я хотел бы обсудить зависимость от `.env` и рассмотреть альтернативный подход. А если быть более точным, то зависимость от библиотеки, которая работает с этим файлом. Мысль моя такова: 

а верно ли то, что приложение устанавливает переменные окружения само по себе из файла? Т.е. по-сути оно мусорит в environment без явного на то разрешения от пользователя. 

Может, подход, при котором приложение принимает ключик, но в то же время, если его не предоставили ищет значение какой-то опции в окружении более "честный"? При таком подходе пользователь сам должен позаботиться о создании окружения для приложения. Мы можем ему предоставить файлик `.env`, который нужно будет импортировать ручками при желании.

А чтение сего всего конфига приложения можно организовать примерно таким образом:

```go
import (
    "flag"
    "os"
)
 
func main() {
    var documentRoot string
    flag.StringVar(&documentRoot, "documentRoot", os.GetEnv("DOCUMENT_ROOT"), "Document root")
    flag.Parse()
}
```

При такой реализации, если у нас не передано значение через ключ, то мы поищем его в окружении. Окружении при этом должно быть заранее подготовлено явно (например, явным импортом файла `.env`). Это может быть полезно также в том случае, если в одном окружении (маловероятно) мы запускаем несколько разных приложений, которые используют одни и те же имена переменных окружения.

**Comment by zoonman** [comment]
Леша, я понимаю твою мысль и мотивы.
Вызов приложения с параметрами/ключиками кажется удобным. Но удобство это такое в некотором плане сомнительное. Тебе всегда будет нужно передавать разные параметры при запуске в разных окружениях. Т.е. командная строка будет меняться и рано или поздно захочется это все переделать и засунуть внутрь какого-нибудь shell-скрипта, который будет запускать демон с нужными параметрами. Переписать файлик на одном, двух серверах не проблема. Но если приложение нужно будет развертывать в разных окружениях автоматически прийдется много чего переделывать.
А если добавить то, что параметров может быть с десяток, то все станет намного хуже. Например у текущего демона на Ноде их 20. А теперь представь, если потребуется поддержка автоматизированного масштабирования? Прийдется писать какие-то скрипты для генерации этого всего хозяйства. Но зачем? Когда уже имеются готовые средства развертывания и управления конфигурацией. Управление через переменные окружения это стандартная практика. Почитай 12FA https://12factor.net/ru/config

**Comment by iamsalnikov** [comment]
Мой основной вопрос не в том, что мы конфигурируем приложение через переменные окружения (принципы 12-факторных приложений я прекрасно знаю и понимаю их, даже руководствуюсь этими принципами в работе). А в том, должно ли приложение само устанавливать эти переменные окружения? В текущей реализации оно само их будет устанавливать. И никак за собой не подчищать после стопа.

-----
Далее оффтоп: 

> Тебе всегда будет нужно передавать разные параметры при запуске в разных окружениях.

Ровно в тот момент, когда мне нужно будет передавать разные параметры для запуска приложения мне понадобятся и разные переменные окружения. Поменять параметр через ключик или переменную окружения - не велика разница, IMHO.

> Но если приложение нужно будет развертывать в разных окружениях автоматически прийдется много чего переделывать

Это весьма сомнительно, с учетом сегодняшних средств доставки приложений. Тогда, когда нам нужно будет поменять что-то поменять при вызове, тогда же нам понадобится что-то поменять и в переменной окружения.

-----

И снова по теме

Т.е. основная мысль такова: разве приложение должно подготовить для себя среду, а не пользователь? 

То есть я ничего не имею против конфигурирования приложения через окружение, вопрос в том, кто должен осуществлять настройку среды.

-----

Вернемся к оффтопу

В том подходе с ключиками, что я предложил не только ведь про ключики. Главное, что там было - возможность перекрыть какую-либо переменную своим собственным значением. Я верю (а если быть точным - знаю), что где-то существуют люди, которые не запускают приложения в изолированных средах, а стартуют их прямо на одной машине пачками. И тогда, когда понадобится запустить даже два экземпляра на одной ноде, а мы все делаем через среду, мы упремся в эти ограничения. Потому что не будем иметь возможности даже банально сменить порт (ведь на том порту, что сейчас в среде указан висит другое приложение).

Ну, а если такие люди - не ЦА, то мы возвращаемся к тому, что, вероятнее всего, мы и так и эдак будем конфигурировать приложение через среду его исполнения. Но кто должен подготовить среду? Приложение ли.

**Comment by iamsalnikov** [comment]
Возможно, у нас просто немного разная идеология. В моем понимании конфигурация - всегда выше приложения. А раз она выше, то и осуществляться она должна не приложением. В идеале - приложение должно лишь ее читать, а не осуществлять конфигурирование самого себя.

А раз это вопрос уже идеологии (на то похоже, т.к. мы оба исповедуем принципы 12fa, но по-разному смотрим на способы их исполнения), то я закрою тикет :) Хотя, можем и похоливарить уже после закрытия.

Я очень надеюсь, что смог-таки объяснить свою позицию. Далеко не с первого раза это обычно получается.

**Comment by zoonman** [comment]
Планы на будущее https://www.linuxquestions.ru/random/o-forume#comment_5a661b5974a1a6022f47f71f
